version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1-python3.11
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__FERNET_KEY: ""
    PYTHONPATH: /opt/airflow
    DATABASE_URL: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
    - ./src:/opt/airflow/src
    - ./data:/opt/airflow/data
  depends_on:
    postgres:
      condition: service_healthy

services:

  postgres:
    image: postgres:16
    container_name: future-skills-postgres
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 5s
      retries: 10

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate &&
        airflow users create \
          --username admin \
          --password admin \
          --firstname Alejo \
          --lastname Admin \
          --role Admin \
          --email admin@admin.com

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always

  dashboard:
    build: ./src/dashboard
    container_name: future-skills-dashboard
    restart: always
    ports:
      - "8501:8501"
    volumes:
      - ./src/dashboard:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  postgres_data: